# Generated by Django 3.0.4 on 2020-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname0', models.CharField(max_length=256)),
                ('Vorname1', models.CharField(max_length=256)),
                ('Vorname2', models.CharField(max_length=256)),
                ('Nachname', models.CharField(max_length=256)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('Vater', models.CharField(max_length=256)),
                ('Mutter', models.CharField(max_length=256)),
                ('Location_born', models.CharField(max_length=256)),
                ('Location_dead', models.CharField(max_length=256, null=True)),
                ('Date_born', models.DateTimeField()),
                ('Date_dead', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'предок',
                'verbose_name_plural': 'предки',
            },
        ),
    ]
