# Generated by Django 3.0.4 on 2020-03-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname0', models.CharField(max_length=256)),
                ('Vorname1', models.CharField(blank=True, max_length=256, null=True)),
                ('Vorname2', models.CharField(blank=True, max_length=256, null=True)),
                ('Nachname', models.CharField(max_length=256)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
            ],
            options={
                'verbose_name': 'предок',
                'verbose_name_plural': 'предки',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role0', models.CharField(choices=[('S', 'Self'), ('V', 'Vater'), ('M', 'Mutter'), ('E', 'Ehemann'), ('F', 'Frau'), ('K', 'Kind')], max_length=1)),
                ('role1', models.CharField(blank=True, choices=[('S', 'Self'), ('V', 'Vater'), ('M', 'Mutter'), ('E', 'Ehemann'), ('F', 'Frau'), ('K', 'Kind')], max_length=1, null=True)),
                ('role2', models.CharField(blank=True, choices=[('S', 'Self'), ('V', 'Vater'), ('M', 'Mutter'), ('E', 'Ehemann'), ('F', 'Frau'), ('K', 'Kind')], max_length=1, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('B', 'geBorn'), ('T', 'geTaufen'), ('H', 'verHeiratet'), ('S', 'Sterben')], max_length=2)),
                ('day', models.CharField(choices=[('M', 'Montag'), ('T', 'Dienstag'), ('W', 'Mittwoch'), ('TU', 'Donnerstag'), ('F', 'Freitag'), ('S', 'Samstag'), ('SU', 'Sonntag')], max_length=2)),
                ('siedlung', models.CharField(max_length=256)),
                ('land', models.CharField(blank=True, max_length=256, null=True)),
                ('member0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member0', to='edit_data.Man', verbose_name='Member0')),
                ('member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member1', to='edit_data.Man', verbose_name='Member1')),
                ('member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member2', to='edit_data.Man', verbose_name='Member2')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
    ]
