# Generated by Django 3.0.4 on 2020-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_data', '0002_auto_20200325_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(choices=[('M', 'Montag'), ('T', 'Dienstag'), ('W', 'Mittwoch'), ('TU', 'Donnerstag'), ('F', 'Freitag'), ('S', 'Samstag'), ('SU', 'Sonntag')], help_text='день недели', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='land',
            field=models.CharField(blank=True, help_text='земля или округ', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='siedlung',
            field=models.CharField(help_text='поселение', max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('B', 'geBorn'), ('T', 'geTaufen'), ('H', 'verHeiratet'), ('S', 'Sterben')], help_text='тип события. рождение, свадьба и тд', max_length=2),
        ),
    ]
