# Generated by Django 3.0.4 on 2020-03-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_data', '0002_auto_20200321_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='Date_dead',
            field=models.DateTimeField(blank=True),
        ),
    ]
